apiVersion: v1
kind: BuildConfig
metadata:
  name: central-api
  namespace: publishing-house
  labels:
    app: central-api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: central-api:latest
  source:
    type: Git
    git:
      uri: https://github.com/rhpds/rhdp-publishing-house.git
      ref: main
    contextDir: central-api
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: central-api
  namespace: publishing-house
  labels:
    app: central-api
spec:
  lookupPolicy:
    local: true
