apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: publishing-house-templates
  description: Publishing House software templates
spec:
  type: url
  targets:
    - ./publishing-house-project/template.yaml
